
ALGORITHM:
  NAME: 'DeepQLearning'
  NUM_EPISODES: 1 
  NUM_STEPS: 100 
  DISCOUNT_FACTOR: 0.9 
  EPSILON_GREEDY: 0.99
  DECAY: 0.99 
  CHANGE_REWARD: False


SOKOBAN:
  DIM: 7
  NUM_BOXES: 1 # 1 / 2
  FIX: True

